# Application Configuration
app_name: zippuff
app_user: zippuff
app_group: zippuff
app_dir: /opt/zippuff
app_port: 59080
app_host: 0.0.0.0

# Python Configuration
python_version: "3.9"
venv_path: "{{ app_dir }}/venv"

# Nginx Configuration
nginx_server_name: "{{ lookup('env', 'NGINX_SERVER_NAME') | default('zippuff.local') }}"
nginx_ssl_cert: "{{ lookup('env', 'NGINX_SSL_CERT') | default('') }}"
nginx_ssl_key: "{{ lookup('env', 'NGINX_SSL_KEY') | default('') }}"

# Environment Variables (will be overridden by .env file)
usps_userid: "{{ lookup('env', 'USPS_USERID') | default('YOUR_USERID') }}"
usps_test_mode: "{{ lookup('env', 'USPS_TEST_MODE') | default('true') }}"
app_debug: "{{ lookup('env', 'APP_DEBUG') | default('false') }}" 