all:
  children:
    zippuff_servers:
      hosts:
        # Multiple hosts deployment (ENABLED)
        host77.nird.club:
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/keys/nirdclub__id_ed25519
          ansible_python_interpreter: /usr/bin/python3
        host78.nird.club:
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/keys/nirdclub__id_ed25519
          ansible_python_interpreter: /usr/bin/python3
      vars:
        app_name: zippuff
        app_user: www-data
        app_group: www-data
        app_dir: /opt/zippuff
        app_port: 59080
        app_host: 0.0.0.0
        python_version: "3.9" 