---
- name: Deploy Zippuff USPS API Tool
  hosts: zippuff_servers
  become: yes
  vars_files:
    - vars/main.yml
  
  vars:
    # Environment variables will be loaded by the deploy.sh script
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
    
    - name: Install required system packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - git
          - curl
        state: present
      when: ansible_os_family == "Debian"
  
  tasks:
    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'
    
    - name: Create logs directory
      file:
        path: "{{ app_dir }}/logs"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'
    
    - name: Copy application files
      copy:
        src: "{{ item }}"
        dest: "{{ app_dir }}/"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0644'
        remote_src: false
      with_fileglob:
        - "../src/*.py"
        - "../requirements.txt"
        - "../README.md"
        - "../LICENSE"
    
    - name: Copy configuration files
      copy:
        src: "{{ item }}"
        dest: "{{ app_dir }}/"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0644'
        remote_src: false
      with_fileglob:
        - "../config/*.yaml"
    
    - name: Copy environment example file
      copy:
        src: "../env.example"
        dest: "{{ app_dir }}/env.example"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0644'
        remote_src: false
    
    - name: Create Python virtual environment
      pip:
        virtualenv: "{{ app_dir }}/venv"
        virtualenv_command: python3 -m venv
        requirements: "{{ app_dir }}/requirements.txt"
        state: present
    
    - name: Create systemd service file
      template:
        src: templates/zippuff-api.service.j2
        dest: /etc/systemd/system/zippuff-api.service
        owner: root
        group: root
        mode: '0644'
      notify: restart zippuff-api
    
    - name: Create web interface systemd service file
      template:
        src: templates/zippuff.service.j2
        dest: /etc/systemd/system/zippuff.service
        owner: root
        group: root
        mode: '0644'
      notify: restart zippuff
    
    - name: Create environment file
      template:
        src: templates/environment.j2
        dest: "{{ app_dir }}/.env"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0600'
      notify: restart zippuff-api
      notify: restart zippuff
    
    - name: Enable and start zippuff-api service
      systemd:
        name: zippuff-api
        enabled: yes
        state: started
        daemon_reload: yes
    
    - name: Enable and start zippuff service
      systemd:
        name: zippuff
        enabled: yes
        state: started
        daemon_reload: yes
          
  handlers:
    - name: restart zippuff-api
      systemd:
        name: zippuff-api
        state: restarted
        daemon_reload: yes
    
    - name: restart zippuff
      systemd:
        name: zippuff
        state: restarted
        daemon_reload: yes
    